package co.com.interkont.cobra.planoperativo.client.dto;
// Generated Jul 12, 2013 4:10:17 PM by Hibernate Tools 3.2.1.GA

import com.google.gwt.user.client.rpc.IsSerializable;
import java.math.BigDecimal;
import java.util.Set;

/**
 * Obrafuenterecursosconvenios generated by hbm2java
 */
public class ObrafuenterecursosconveniosDTO implements IsSerializable {

    private int idobrafuenterecursos;
    private ObraDTO obra;
    private FuenterecursosconvenioDTO fuenterecursosconvenio;
    private String rubro;
    /*si tipoaporte es 0 es dinero si es 1 es especie*/
    private int tipoaporte;
    private int vigencia;
    private BigDecimal valor;
    private BigDecimal valorDisponible;
    private BigDecimal pagodirecto;
    private BigDecimal otrospagos;
    /*si forma de ingreso es 0 es valor si es 1 es porcentaje*/
    private int formaingreso;
    private BigDecimal porcentaje;
    /*valores necesarios para cargar la tabla de obra fuente recursos*/
    private String nombreEntidad;
    private String eliminar;
    private String descripcionaporte="";
    private String nombreEntidadTipo;
    private boolean estaEnFuenteRecurso;

    public ObrafuenterecursosconveniosDTO() {
    }

    public ObrafuenterecursosconveniosDTO(int idobrafuenterecursos, ObraDTO obra, int tipoaporte, int vigencia, BigDecimal valor) {
        this.idobrafuenterecursos = idobrafuenterecursos;
        this.obra = obra;
        this.tipoaporte = tipoaporte;
        this.vigencia = vigencia;
        this.valor = valor;
    }

    public ObrafuenterecursosconveniosDTO(int tipoaporte, BigDecimal valor, FuenterecursosconvenioDTO fuente, String rubro, int id) {
        this.tipoaporte = tipoaporte;
        this.valor = valor;
        this.fuenterecursosconvenio = fuente;
        this.rubro = rubro;
        this.valorDisponible = valor;
        this.idobrafuenterecursos = id;
        if (tipoaporte == 1) {
            descripcionaporte = "Dinero";
        } else {
            descripcionaporte = "Especie";
        }
        nombreEntidad = fuente.getTercero().getStrnombrecompleto();
        this.eliminar = "Eliminar";
    }

    public ObrafuenterecursosconveniosDTO(BigDecimal valor, FuenterecursosconvenioDTO fuente, String rubro, int id, int vigencia, int tipoAporte, int formaPago,int idTemp) {
        this.idobrafuenterecursos=idTemp;
        this.tipoaporte = 0;
        this.valor = valor;
        this.fuenterecursosconvenio = fuente;
        this.rubro = rubro;
        this.valorDisponible = valor;
        this.idobrafuenterecursos = id;
        this.vigencia = vigencia;
        this.tipoaporte = tipoAporte;
        this.formaingreso = formaPago;
        if (tipoaporte == 0) {
            descripcionaporte = "Dinero";
        } else {
            descripcionaporte = "Especie";
        }
        nombreEntidad = fuente.getTercero().getStrnombrecompleto();        
        this.eliminar = "Eliminar";
    }

    public ObrafuenterecursosconveniosDTO(BigDecimal valor, FuenterecursosconvenioDTO fuente, String rubro, int id, int vigencia, BigDecimal porcentaje, int tipoAporte, int formaPago) {
        this.tipoaporte = 0;
        this.valor = valor;
        this.fuenterecursosconvenio = fuente;
        this.rubro = rubro;
        this.valorDisponible = valor;
        this.idobrafuenterecursos = id;
        this.vigencia = vigencia;
        this.tipoaporte = tipoAporte;
        this.formaingreso = formaPago;
        if (tipoaporte == 0) {
            descripcionaporte = "Dinero";
        } else {
            descripcionaporte = "Especie";
        }
        nombreEntidad = fuente.getTercero().getStrnombrecompleto();
        this.nombreEntidadTipo = nombreEntidad + "-" + descripcionaporte;
        this.eliminar = "Eliminar";
        this.porcentaje = porcentaje;
    }

    public ObrafuenterecursosconveniosDTO(String descripcionAporte, FuenterecursosconvenioDTO fuente, String rubro, int id, int vigencia,int idTemp) {
        this.tipoaporte = 0;
        this.fuenterecursosconvenio = fuente;
        this.rubro = rubro;
        this.idobrafuenterecursos = id;
        this.vigencia = vigencia;
        this.tipoaporte = 1;
        this.descripcionaporte = "Especie";
        nombreEntidad = fuente.getTercero().getStrnombrecompleto();
        this.eliminar = "Eliminar";
        this.idobrafuenterecursos=idTemp;
        this.nombreEntidadTipo = nombreEntidad + "-" + descripcionaporte;
    }

    public ObrafuenterecursosconveniosDTO(int idobrafuenterecursos, ObraDTO obra, FuenterecursosconvenioDTO fuenterecursosconvenio, String rubro, int tipoaporte, int vigencia, BigDecimal valor, String descripcionaporte, Set relacionobrafuenterecursoscontratos) {
        this.idobrafuenterecursos = idobrafuenterecursos;
        this.obra = obra;
        this.fuenterecursosconvenio = fuenterecursosconvenio;
        this.rubro = rubro;
        this.tipoaporte = tipoaporte;
        this.vigencia = vigencia;
        this.valor = valor;
        this.descripcionaporte = descripcionaporte;

    }

    /**
     * @return the idobrafuenterecursos
     */
    public int getIdobrafuenterecursos() {
        return idobrafuenterecursos;
    }

    /**
     * @param idobrafuenterecursos the idobrafuenterecursos to set
     */
    public void setIdobrafuenterecursos(int idobrafuenterecursos) {
        this.idobrafuenterecursos = idobrafuenterecursos;
    }

    /**
     * @return the obra
     */
    public ObraDTO getObra() {
        return obra;
    }

    /**
     * @param obra the obra to set
     */
    public void setObra(ObraDTO obra) {
        this.obra = obra;
    }

    /**
     * @return the fuenterecursosconvenio
     */
    public FuenterecursosconvenioDTO getFuenterecursosconvenio() {
        return fuenterecursosconvenio;
    }

    /**
     * @param fuenterecursosconvenio the fuenterecursosconvenio to set
     */
    public void setFuenterecursosconvenio(FuenterecursosconvenioDTO fuenterecursosconvenio) {
        this.fuenterecursosconvenio = fuenterecursosconvenio;
    }

    /**
     * @return the rubro
     */
    public String getRubro() {
        return rubro;
    }

    /**
     * @param rubro the rubro to set
     */
    public void setRubro(String rubro) {
        this.rubro = rubro;
    }

    /**
     * @return the tipoaporte
     */
    public int getTipoaporte() {
        return tipoaporte;
    }

    /**
     * @param tipoaporte the tipoaporte to set
     */
    public void setTipoaporte(int tipoaporte) {
        this.tipoaporte = tipoaporte;
    }

    /**
     * @return the vigencia
     */
    public int getVigencia() {
        return vigencia;
    }

    /**
     * @param vigencia the vigencia to set
     */
    public void setVigencia(int vigencia) {
        this.vigencia = vigencia;
    }

    /**
     * @return the valor
     */
    public BigDecimal getValor() {
        return valor;
    }

    /**
     * @param valor the valor to set
     */
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    /**
     * @return the descripcionaporte
     */
    public String getDescripcionaporte() {
        return descripcionaporte;
    }

    /**
     * @param descripcionaporte the descripcionaporte to set
     */
    public void setDescripcionaporte(String descripcionaporte) {
        this.descripcionaporte = descripcionaporte;
    }

    /**
     * @return the valorDisponible
     */
    public BigDecimal getValorDisponible() {
        return valorDisponible;
    }

    /**
     * @param valorDisponible the valorDisponible to set
     */
    public void setValorDisponible(BigDecimal valorDisponible) {
        this.valorDisponible = valorDisponible;
    }

    /**
     * @return the nombreEntidad
     */
    public String getNombreEntidad() {
        return nombreEntidad;
    }

    /**
     * @param nombreEntidad the nombreEntidad to set
     */
    public void setNombreEntidad(String nombreEntidad) {
        this.nombreEntidad = nombreEntidad;
    }

    /**
     * @return the eliminar
     */
    public String getEliminar() {
        return eliminar;
    }

    /**
     * @param eliminar the eliminar to set
     */
    public void setEliminar(String eliminar) {
        this.eliminar = eliminar;
    }

    /**
     * @return the pagodirecto
     */
    public BigDecimal getPagodirecto() {
        return pagodirecto;
    }

    /**
     * @param pagodirecto the pagodirecto to set
     */
    public void setPagodirecto(BigDecimal pagodirecto) {
        this.pagodirecto = pagodirecto;
    }

    /**
     * @return the otrospagos
     */
    public BigDecimal getOtrospagos() {
        return otrospagos;
    }

    /**
     * @param otrospagos the otrospagos to set
     */
    public void setOtrospagos(BigDecimal otrospagos) {
        this.otrospagos = otrospagos;
    }

    /**
     * @return the formaingreso
     */
    public int getFormaingreso() {
        return formaingreso;
    }

    /**
     * @param formaingreso the formaingreso to set
     */
    public void setFormaingreso(int formaingreso) {
        this.formaingreso = formaingreso;
    }

    /**
     * @return the porcentaje
     */
    public BigDecimal getPorcentaje() {
        return porcentaje;
    }

    /**
     * @param porcentaje the porcentaje to set
     */
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }

    /**
     * @return the nombreEntidadTipo
     */
    public String getNombreEntidadTipo() {
        nombreEntidadTipo = nombreEntidad + "-" + descripcionaporte;        
        return nombreEntidadTipo;
    }

    /**
     * @param nombreEntidadTipo the nombreEntidadTipo to set
     */
    public void setNombreEntidadTipo(String nombreEntidadTipo) {
        this.nombreEntidadTipo = nombreEntidadTipo;
    }

    /**
     * @return the estaEnFuenteRecurso
     */
    public boolean isEstaEnFuenteRecurso() {
        return estaEnFuenteRecurso;
    }

    /**
     * @param estaEnFuenteRecurso the estaEnFuenteRecurso to set
     */
    public void setEstaEnFuenteRecurso(boolean estaEnFuenteRecurso) {
        this.estaEnFuenteRecurso = estaEnFuenteRecurso;
    }
}
