package co.com.interkont.cobra.planoperativo.client.dto;
// Generated Jul 19, 2013 12:35:10 PM by Hibernate Tools 3.2.1.GA



import java.io.Serializable;
import co.com.interkont.cobra.to.RelaciontipoobraalarmaId;




/**
 * RelaciontipoobraalarmaId generated by hbm2java
 */
public class RelaciontipoobraalarmaIdDTO  implements Serializable {


     private int inttipoobra;
     private int intidalarma;

    public RelaciontipoobraalarmaIdDTO() {
    }

    public RelaciontipoobraalarmaIdDTO(int inttipoobra, int intidalarma) {
       this.inttipoobra = inttipoobra;
       this.intidalarma = intidalarma;
    }
    
    public RelaciontipoobraalarmaIdDTO(RelaciontipoobraalarmaId relaciontipoobraalarmaId) {
        this.inttipoobra=relaciontipoobraalarmaId.getInttipoobra();
        this.intidalarma=relaciontipoobraalarmaId.getIntidalarma();
    }
   
    public int getInttipoobra() {
        return this.inttipoobra;
    }
    
    public void setInttipoobra(int inttipoobra) {
        this.inttipoobra = inttipoobra;
    }
    public int getIntidalarma() {
        return this.intidalarma;
    }
    
    public void setIntidalarma(int intidalarma) {
        this.intidalarma = intidalarma;
    }


     @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelaciontipoobraalarmaIdDTO) ) return false;
		 RelaciontipoobraalarmaIdDTO castOther = ( RelaciontipoobraalarmaIdDTO ) other; 
         
		 return (this.getInttipoobra()==castOther.getInttipoobra())
 && (this.getIntidalarma()==castOther.getIntidalarma());
   }
   
     @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInttipoobra();
         result = 37 * result + this.getIntidalarma();
         return result;
   }   


}


