package co.com.interkont.cobra.planoperativo.client.dto;
// Generated Jul 19, 2013 12:35:10 PM by Hibernate Tools 3.2.1.GA


import co.com.interkont.cobra.to.Semaforo;
import com.google.gwt.user.client.rpc.IsSerializable;





/**
 * Semaforo generated by hbm2java
 */
public class SemaforoDTO  implements IsSerializable {


     private int intidsemaforo;
     private AlarmaDTO alarma;
     private int intporini;
     private int intporfin;
     private String strimagen;
     private boolean booleanatraso;

    public SemaforoDTO() {
    }

    public SemaforoDTO(int intidsemaforo, AlarmaDTO alarma, int intporini, int intporfin, String strimagen, boolean booleanatraso) {
       this.intidsemaforo = intidsemaforo;
       this.alarma = alarma;
       this.intporini = intporini;
       this.intporfin = intporfin;
       this.strimagen = strimagen;
       this.booleanatraso = booleanatraso;
    }
    
     public SemaforoDTO(Semaforo semaforo) {
         this.intidsemaforo=semaforo.getIntidsemaforo();
//        this.alarma=new AlarmaDTO(semaforo.getAlarma());
        this.intporfin=semaforo.getIntporfin();
        this.strimagen=semaforo.getStrimagen();
        this.booleanatraso=semaforo.isBooleanatraso();
        
    }
   
    public int getIntidsemaforo() {
        return this.intidsemaforo;
    }
    
    public void setIntidsemaforo(int intidsemaforo) {
        this.intidsemaforo = intidsemaforo;
    }
    public AlarmaDTO getAlarma() {
        return this.alarma;
    }
    
    public void setAlarma(AlarmaDTO alarma) {
        this.alarma = alarma;
    }
    public int getIntporini() {
        return this.intporini;
    }
    
    public void setIntporini(int intporini) {
        this.intporini = intporini;
    }
    public int getIntporfin() {
        return this.intporfin;
    }
    
    public void setIntporfin(int intporfin) {
        this.intporfin = intporfin;
    }
    public String getStrimagen() {
        return this.strimagen;
    }
    
    public void setStrimagen(String strimagen) {
        this.strimagen = strimagen;
    }
    public boolean isBooleanatraso() {
        return this.booleanatraso;
    }
    
    public void setBooleanatraso(boolean booleanatraso) {
        this.booleanatraso = booleanatraso;
    }




}


